# Generated by Django 4.0.1 on 2022-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_for_subscription', models.CharField(max_length=4, unique=True)),
                ('Time_for_subcriptions', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
