# Generated by Django 4.0.1 on 2022-03-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddSongs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsname',
            name='song_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
