# Generated by Django 4.0.1 on 2022-02-26 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_subcription',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
