# Generated by Django 4.0.1 on 2022-02-26 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_useraccount_date_of_subcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_subcription',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 27, 0, 9, 50, 766641)),
        ),
    ]
