# Generated by Django 4.0.1 on 2022-02-27 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_useraccount_date_of_subcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_subcription',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 28, 1, 1, 39, 878099)),
        ),
    ]
