# Generated by Django 4.0.1 on 2022-03-01 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_useraccount_date_of_subcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_subcription',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 1, 19, 36, 26, 110702)),
        ),
    ]
