# Generated by Django 4.0.1 on 2022-03-08 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_useraccount_date_of_subcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_subcription',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 8, 15, 53, 42, 825800)),
        ),
    ]
