# Generated by Django 4.0.1 on 2022-02-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AddSongs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('reviews', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('song_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_data', to='AddSongs.songsname')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
