# Generated by Django 4.0.1 on 2022-02-24 19:19

import Reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviews',
            name='reviews',
            field=models.CharField(max_length=200, validators=[Reviews.models.validate_reviews]),
        ),
    ]
