# Generated by Django 4.0.1 on 2022-02-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddImageForModeCheckUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddImageForModeCheckUserField', models.ImageField(help_text='Maximum file size allowed is 5MB', upload_to='image/list/')),
            ],
        ),
    ]
