# Generated by Django 4.0.1 on 2022-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddImageForModeCheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_in_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy', models.IntegerField(blank=True, default=1, null=True)),
                ('sad', models.IntegerField(blank=True, default=1, null=True)),
                ('neutral', models.IntegerField(blank=True, default=1, null=True)),
                ('fear', models.IntegerField(blank=True, default=1, null=True)),
                ('diguest', models.IntegerField(blank=True, default=1, null=True)),
                ('surprise', models.IntegerField(blank=True, default=1, null=True)),
                ('angry', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
